### ISSUE TITLE
Restrict data value entries to eliminate typos

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#18]
Looks like we can restrict the range of acceptable values in the ODK form definition. See [here](http://build.opendatakit.org/) for numerical example. W+J recommended restricting values like so:
- Influent - none
- Settled - 20.0 NTU (should be well below this, and this lets us see if plants without filters are failing 5.0 NTU standard)
- Filtered - 5.0 NTU
- Coagulant Dose - 50 mg/L (most CDC's are designed for max dose of 30-40 mg/L)

Also, the message for when the boundaries are exceeded should read something like "We think this is a typo... value should be between X and Y. If this is not a typo, please enter '0.0' and include the real value in the comments section"

Walker and John, what do you think the wording shoud be? both in Spanish and English?

**Comment by jonschristensen** [comment]
Can we give them an option to keep the value if it is not a typo, instead of doing the comments thing?

"The value you have entered is outside the expected range (X-Y). Please enter the value again to confirm."

"El valor que ha entrado cae fuera del rango esperado (X-Y). Haga el favor de entrar el dato de nuevo para confirmarlo."

**Comment by jacuerp** [comment]
@ethan92429  @jonschristensen I implemented this on TEST_Datos_v1.4

Inputs on those fields outside the specified ranges will prevent the form from continuing, and invoke a warning message. Check it out and see if it's what you had in mind. However, if you want the option to keep the extreme values I'll have to think a little bit more about how to restructure the form.

**Comment by ethan92429** [comment]
@jacuerp I like this! The warning shows up as a toast message. @jonschristensen, here is a screenshot. 
![screenshot_2016-06-28-10-56-54](https://cloud.githubusercontent.com/assets/8585379/16420414/3e43166a-3d1f-11e6-8406-d3bb26cea8e0.png)

**Comment by jonschristensen** [comment]
@jacuerp I like the pop-up. We won't want these restrictions to be absolute, however. There are unusual cases where the values will truly fall outside the expected range. Is there some way to give them the option to confirm an unusual value? Or bypass the restriction?

Also, because of Spanish genders "El TURBIEDAD..." is technically grammatically incorrect, how about "El valor de TURBIEDAD..." or alternatively "El/la TURBIEDAD..."

**Comment by jacuerp** [comment]
@jonschristensen I didn't implement that functionality because it was non-trivial, but I've found a workaround that will be easy to implement. I'll need help with the wording/translation so it's not too complicated. 

If values outside the expected range are entered, another screen will show with a yes/no selection, and this label: "The value you have entered is outside the expected range (X-Y). Please GO BACK to change your entry, or SELECT YES to save and continue." No will be selected by default, and they won't be allowed to continue without selecting 'yes'

**Comment by jonschristensen** [comment]
@jacuerp This sounds good, in Spanish it'll be something like:

"El valor que ha entrado cae fuera del rango esperado (X-Y). Por favor, VOLVER para cambiar el dato, o SELECCIONAR SÍ para guardarlo y seguir."

**Comment by ethan92429** [comment]
Well done, I like the option for proceeding.

**Comment by ethan92429** [comment]
This has been implemented in 1.4 which is currently out in the wild at Moroceli so I'm going to close this issue
