### ISSUE TITLE
Add a path for inserting a new plant that doesn't require a whole new form

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/POST#25]
Currently, when we add a plant, we have to push out a whole new form that includes that plant name, number of filters, etc. However, pushing out a new form is challenging because it requires every operator to manually switch to the new form which is hard to communicate, and it requires a data migration. The solution (I think) is already possible in ODK using [dynamically loaded multi choice data.](https://opendatakit.org/help/form-design/data-preloading/) Eventually, we'll want a method for adding plants that anyone who has access will have the ability to use. This will probably be in the form of a Google Form that sends info to a google spreadsheet that gets turned into the csv and uploaded to the server upon every update.

**Comment by jacuerp** [comment]
@ethan92429 'Datos v1.5.XLSForm' is on the development server and ready for testing! This is the full port to the XLSForm which can be found in data>Collection Forms and Plant Param Sheets. It doesn't have support for arbitrary filter numbers, but it does support Las Vegas's 6 filters so it works for now while I work on the more sustainable solution. It also includes csv preloading for easier updates.

A few notes:

- I changed the format of the survey so that each question appears on its own page. I did this because I personally have trouble scrolling through the entire field-list of plantData fields and imagine it's difficult for the operators as well. On top of this, ODK has an unavoidable page reloading 'feature' which causes the survey to jump back up to the top after sending intents to post.DOSE and post.BLUETOOTH. We all agreed it would be a useful switch. Let us know your thoughts!
- I need a translation for the hint about making sure dosage tubes are open.
- The dosage tube hint can also appear as a separate 'acknowledge' type question, similar to the warning pages for trubidity values outside the expected range.

**Comment by ethan92429** [comment]
The new form looks great. I think the switches to arrows instead of swiping is great. For ensuring the correct number of dosing tubes is open, just write the hint as: "Asegurarse de que el número correcto de tubos de dosificación está abierto"
I think just a hint should be fine. I think an acknowledge type would just frustrate them.
