### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by jacuerp** [AguaClara/POST#27]
@asm278 @danelimjoco Welcome to POST Issue Tracking! Once the new BT Turb and Dosage Rec modules go online, 'issues' will be your history and main line of communication with Ethan (@ethan92429) during the debugging/improvement process. 

Use this issue to get acquainted!

**Comment by danelimjoco** [comment]
@ethan92429 
Hi Ethan! I'm Dane and this semester I'll be working on the bluetooth turbidity module. I'm excited to get it up and running and although I don't have much experience with Android development, I'll try my best to make it happen. Looking forward to meeting you next Wednesday!

**Comment by ethan92429** [comment]
@danelimjoco 
Hi Dane! So glad to hear you'll be working on the Bluetooth module! You can use these issues at any point to contact me. I think they are nice because they focus the conversation on one actionable item. I highly recommend reading this: https://guides.github.com/features/issues/ . You can even include references to issues directly in your commits! 

I am currently one of the AC engineers down in Honduras, and so part of my job is to integrate POST well with our operator training here. I started POST last spring with a team of 3 people as a CS masters student in an effort to tighten the feedback loop between plant data and the people who benefit from it (operators, investors and engineers). 

Sometimes, I'll make issues when I see problems in the field or have an idea for a new feature. We use them to track everything. Whenever you come up with a different way to resolve a feature, or you have an opinion about the feature, please write it into the issue thread so we can continue the conversation. 

Please always feel free to reach out to me about anything! Looking forward to meeting you!

**Comment by asm278** [comment]
Hello @ethan92429 !
I'm Andrew, and I will be starting out this semester by making a native app to make suggestions for coagulant doses #10. Haven't done much with Android, but I'm having fun with the Java!

**Comment by ethan92429** [comment]
Hi @asm278! 
Nice to hear from you again :). I hear you are making this into your Masters of Engineering project! How exciting! I can't wait to start brainstorming some ways to turn our data into useful insights for the operators. Even just the coagulant dose estimator can run extremely deep. Can't wait to hear your ideas and deploy some production code!
