### ISSUE TITLE
POST is racking up charges on google cloud

### ISSUE THREAD

**Issue by monroews** [AguaClara/POST#3]
The current bill is $53.94 since March 8.
I don't have authorization to see the bill, so I don't know what the bill is for. Could one of you please investigate what is causing this new bill generation? Also, it would be very good if members of the team were notified when bills are accumulating so that you know to investigate.

**Comment by eak24** [comment]
Hmm... this seems to be a perennial recurrence. Sorry!

I think I isolated the problem. Our ODK aggregate server is attempting to publish data to Fusion Tables every few seconds. This was both keeping the instance active, racking up instance frontend hours and eating up the data quota. According to [this post](https://groups.google.com/forum/#!topic/opendatakit/piphw3nOo9I) we can reduce data operations by checking a box in site_admin -> preferences. I did this on both the production and development server. I'm still not sure why it went over this month and not last... perhaps because we've been spinning up the development server to deploy a new form. Let's keep monitoring the daily cost to ensure the problem has been fixed. I also set the budget at $1/day, so we should be warned more rapidly. There apparently is no easy way to add additional emails to the budget alert system - only the administrator gets those, according to [this page on setting budgets and alerts](https://cloud.google.com/billing/docs/how-to/budgets). @monroews hope that solves it! Let me know ASAP if you get another email. - you can just forward them to my email. Technically we should never be going over the free quotas.
