### ISSUE TITLE
Managing Google Apps Scripts with Github

### ISSUE THREAD

**Issue by asm278** [AguaClara/POST#35]
@ethan92429 I found an article [here](https://developers.googleblog.com/2015/12/advanced-development-process-with-apps.html) which looks like (among other things) it establishes version control for Google Apps Scripts. 

I haven't read too much into the setup process, but if the overhead isn't too large. This would make managing scripts easier, especially tracking changes.

**Comment by asm278** [comment]
@jacuerp thoughts?

**Comment by ethan92429** [comment]
Thanks for looking into this. We should be version tracking the scripts in Github. I say go ahead and investigate! According to the comments this node looks like it should still work. Happy hunting.

**Comment by ethan92429** [comment]
As far as I understand, we're deciding not to pursue this further because the only automated solutions are not very well developed, and manually adding the scripts is very cumbersome and requires too much work. Therefore we are just using the apps scripts limited version control that is built into the apps scripts program [explained here.](https://developers.google.com/apps-script/guide_versions) Basically you can save different versions of the code. It doesn't offer any of the features of github like comparing commits, branching or other things, but should suffice until a better automated version control comes out.
